version: '3.9'
services:
  gateway:
    image: gateway
    build: gateway/
    ports:
      - 14005:14005
    volumes:
      - ./indices:/indices
    extra_hosts:
      - "host.docker.internal:host-gateway"

  index_service_0:
    image: index_service
    build: index_service/
    ports:
      - 14000:14000
    volumes:
      - ./indices:/indices
    environment:
      - CLUSTER_ID=0
    extra_hosts:
      - "host.docker.internal:host-gateway"

  index_service_1:
    image: index_service
    build: index_service/
    ports:
      - 14001:14000
    volumes:
      - ./indices:/indices
    environment:
      - CLUSTER_ID=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  index_service_2:
    image: index_service
    build: index_service/
    ports:
      - 14002:14000
    volumes:
      - ./indices:/indices
    environment:
      - CLUSTER_ID=2
    extra_hosts:
      - "host.docker.internal:host-gateway"

  index_service_3:
    image: index_service
    build: index_service/
    ports:
      - 14003:14000
    volumes:
      - ./indices:/indices
    environment:
      - CLUSTER_ID=3
    extra_hosts:
      - "host.docker.internal:host-gateway"
