version: '3.7'
services:
  tf_serving:
    image: tensorflow/serving:2.2.0
    volumes:
      - "/opt/models:/models/use"
    environment:
      MODEL_NAME: "use"
    ports:
      - "8501:8501"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gateway:
    image: 95.217.236.128:5000/gateway
    build: gateway/
    ports:
      - 14005:14005
    volumes:
      - /opt/indices/:/indices
    extra_hosts:
      - "host.docker.internal:host-gateway"

  index_service_0:
    image: 95.217.236.128:5000/index_service
    build: index_service/
    ports:
      - 14000:14000
    volumes:
      - /opt/indices/:/indices
    environment:
      - CLUSTER_ID=0
    extra_hosts:
      - "host.docker.internal:host-gateway"

  index_service_1:
    image: 95.217.236.128:5000/index_service
    build: index_service/
    ports:
      - 14001:14000
    volumes:
      - /opt/indices/:/indices
    environment:
      - CLUSTER_ID=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  index_service_2:
    image: 95.217.236.128:5000/index_service
    build: index_service/
    ports:
      - 14002:14000
    volumes:
      - /opt/indices/:/indices
    environment:
      - CLUSTER_ID=2
    extra_hosts:
      - "host.docker.internal:host-gateway"

  index_service_3:
    image: 95.217.236.128:5000/index_service
    build: index_service/
    ports:
      - 14003:14000
    volumes:
      - /opt/indices/:/indices
    environment:
      - CLUSTER_ID=3
    extra_hosts:
      - "host.docker.internal:host-gateway"
